name: Lint

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:  # Allows manual triggering

jobs:
  lint:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false

    steps:
    - uses: actions/checkout@main

    - name: Install the latest version of uv
      uses: astral-sh/setup-uv@v5
      with:
        enable-cache: true

    - name: Lint with ruff
      run: |
        uvx --with cryptography ruff check

    - name: Type check with mypy
      run: |
        uvx --with cryptography mypy httpx_pkcs12
